name: Windows

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64, x86]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: vulkansdk
        run: |
          Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.1.92.1/windows/VulkanSDK-1.1.92.1-Installer.exe?Human=true -OutFile VulkanSDK-1.1.92.1-Installer.exe
          7z x ./VulkanSDK-1.1.92.1-Installer.exe -oVulkanSDK

      - name: configure
        run: |
          $env:VULKAN_SDK="$(pwd)/VulkanSDK"
          mkdir build; cd build
          cmake -DNCNN_VULKAN=ON ..

      - name: Build
        run: |
          echo y | xmake e
